### ISSUE TITLE
compatibility with pytorch 1.0+

### ISSUE THREAD

**Issue by 0oshowero0** [LaceyChen17/lambda-opt#1]

**Comment by yihong-chen** [comment]
work well under pytorch 1.1.0

**Comment by yihong-chen** [comment]
under pytorch 1.2.0, this bug surfaces

> Traceback (most recent call last):
File "./train_ml1m_alter.py", line 121, in <module>
engine.train()
File "/home/yihochen/adaptive-l0-regularizer/src/engine.py", line 256, in train
self.train_alter_reg()
File "/home/yihochen/adaptive-l0-regularizer/src/engine.py", line 133, in train_alter_reg
self.train_an_episode(self._opt['max_steps'])
File "/home/yihochen/adaptive-l0-regularizer/src/engine.py", line 163, in train_an_episode
curr_lambda = self._regularizer.get_lambda(status=status)
File "/home/yihochen/adaptive-l0-regularizer/src/regularizer/regularizer.py", line 290, in get_lambda
lamba=self.init_lambda()) # assumed param update without regularization, self.init_lambda return zero initialization
File "/home/yihochen/adaptive-l0-regularizer/src/factorizer/factorizer.py", line 214, in update
self.optimizer.step()
File "/home/yihochen/anaconda3/envs/py37torch12/lib/python3.7/site-packages/torch/optim/lr_scheduler.py", line 36, in wrapper
return func(*args, **kwargs)
File "/home/yihochen/anaconda3/envs/py37torch12/lib/python3.7/site-packages/torch/optim/lr_scheduler.py", line 36, in wrapper
return func(*args, **kwargs)
File "/home/yihochen/anaconda3/envs/py37torch12/lib/python3.7/site-packages/torch/optim/lr_scheduler.py", line 36, in wrapper
return func(*args, **kwargs)
[Previous line repeated 988 more times]
File "/home/yihochen/anaconda3/envs/py37torch12/lib/python3.7/site-packages/torch/optim/adam.py", line 69, in step
state = self.state[p]
File "/home/yihochen/anaconda3/envs/py37torch12/lib/python3.7/site-packages/torch/tensor.py", line 393, in hash
return id(self)
RecursionError: maximum recursion depth exceeded while calling a Python object

**Comment by yihong-chen** [comment]
Solved. Thanks to @0oshowero0 . See pull request #2 for details.
